# Generated by Django 4.0.4 on 2022-06-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentdetail',
            fields=[
                ('roll_number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('mobile', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=30)),
                ('sem', models.IntegerField()),
                ('dob', models.DateField()),
            ],
        ),
    ]
