# Generated by Django 4.0.4 on 2022-06-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='facultydetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('f_department', models.CharField(max_length=30)),
                ('f_mobile', models.IntegerField()),
            ],
        ),
    ]
